week 6 changes
Currently a bug is causing this to be broken

In rdui.py in the RDojo_UI class
# AttributeError: 'module' object has no attribute 'menutItem' #